export const bars = [
  {
    id: 1,
    name: "Kneipe Fasan",
    address: "Eichenstraße 10, 20253 Hamburg",
    phone: "040-123456789",
    email: "info@sportsbarxyz.com",
    website: "http://www.sportsbarxyz.com",
    openingHours: {
      monday: "16:00 - 02:00",
      tuesday: "16:00 - 02:00",
      wednesday: "16:00 - 02:00",
      thursday: "16:00 - 02:00",
      friday: "16:00 - 03:00",
      saturday: "12:00 - 03:00",
      sunday: "12:00 - 02:00",
    },
    reviews: [
      {
        username: "JohnDoe",
        rating: 4,
        comment: "Great atmosphere and friendly staff.",
      },
      {
        username: "JaneSmith",
        rating: 5,
        comment: "Best place to watch sports in town!",
      },
    ],
    specialties: [
      "Craft beers",
      "Gourmet burgers",
      "Live sports events",
      "Pool tables",
    ],
    images: [
      "http://www.sportsbarxyz.com/images/interior1.jpg",
      "http://www.sportsbarxyz.com/images/interior2.jpg",
    ],
    location: {
      latitude: 53.551086,
      longitude: 9.993682,
    },
    socialMedia: {
      facebook: "http://www.facebook.com/sportsbarxyz",
      twitter: "http://www.twitter.com/sportsbarxyz",
      instagram: "http://www.instagram.com/sportsbarxyz",
    },
    beerPrices: {
      pils: 3.5,
    },
  },
  {
    id: 2,
    name: "Le Lion Bar de Paris",
    address: "Rathausstraße 3, 20095 Hamburg",
    phone: "040-987654321",
    email: "info@kickoffpub.com",
    website: "http://www.kickoffpub.com",
    openingHours: {
      monday: "17:00 - 01:00",
      tuesday: "17:00 - 01:00",
      wednesday: "17:00 - 01:00",
      thursday: "17:00 - 02:00",
      friday: "17:00 - 03:00",
      saturday: "12:00 - 03:00",
      sunday: "12:00 - 01:00",
    },
    reviews: [
      {
        id: 1,
        username: "SoccerFan99",
        rating: 4,
        comment: "Great selection of beers and big screens for watching games.",
      },
      {
        id: 2,
        username: "SportsLover123",
        rating: 5,
        comment: "Awesome atmosphere during live matches!",
      },
    ],
    specialties: [
      "International beers",
      "Nachos and wings",
      "Foosball tables",
      "Beer garden",
    ],
    images: [
      "http://www.kickoffpub.com/images/interior1.jpg",
      "http://www.kickoffpub.com/images/interior2.jpg",
    ],
    location: {
      latitude: 53.561764,
      longitude: 10.01854,
    },
    socialMedia: {
      facebook: "http://www.facebook.com/kickoffpub",
      twitter: "http://www.twitter.com/kickoffpub",
      instagram: "http://www.instagram.com/kickoffpub",
    },
    beerPrices: {
      pils: 4,
    },
  },
  {
    id: 3,
    name: "Clockers",
    address: "Kleine Rainstraße 10, 22765 Hamburg",
    phone: "040-123456789",
    email: "info@fanzonesportsbar.com",
    website: "http://www.fanzonesportsbar.com",
    openingHours: {
      monday: "16:00 - 01:00",
      tuesday: "16:00 - 01:00",
      wednesday: "16:00 - 01:00",
      thursday: "16:00 - 02:00",
      friday: "16:00 - 03:00",
      saturday: "12:00 - 03:00",
      sunday: "12:00 - 01:00",
    },
    reviews: [
      {
        id: 1,
        username: "FootballFanatic",
        rating: 5,
        comment: "Best place in town to watch football games!",
      },
      {
        id: 2,
        username: "SportsEnthusiast",
        rating: 4,
        comment: "Great atmosphere and friendly staff.",
      },
    ],
    specialties: [
      "Craft beers",
      "Burgers and fries",
      "Pool tables",
      "Outdoor seating",
    ],
    images: [
      "http://www.fanzonesportsbar.com/images/interior1.jpg",
      "http://www.fanzonesportsbar.com/images/interior2.jpg",
    ],
    location: {
      latitude: 53.548536,
      longitude: 9.990018,
    },
    socialMedia: {
      facebook: "http://www.facebook.com/fanzonesportsbar",
      twitter: "http://www.twitter.com/fanzonesportsbar",
      instagram: "http://www.instagram.com/fanzonesportsbar",
    },
    beerPrices: {
      pils: 4.5,
    },
  },
  {
    id: 4,
    name: "Pony Bar",
    address: "Allende-Platz 1, 20146 Hamburg",
    phone: "040-987654321",
    email: "info@biergarten-loewen.com",
    website: "http://www.biergarten-loewen.com",
    openingHours: {
      monday: "17:00 - 00:00",
      tuesday: "17:00 - 00:00",
      wednesday: "17:00 - 00:00",
      thursday: "17:00 - 01:00",
      friday: "17:00 - 02:00",
      saturday: "12:00 - 02:00",
      sunday: "12:00 - 00:00",
    },
    reviews: [
      {
        id: 1,
        username: "BeerLover",
        rating: 4,
        comment: "Authentic German beer garden experience!",
      },
      {
        id: 2,
        username: "BarHopper",
        rating: 3,
        comment: "Nice outdoor seating area, but limited beer selection.",
      },
    ],
    specialties: ["German beers", "Pretzels", "Sausages", "Live music"],
    images: [
      "http://www.biergarten-loewen.com/images/beer-garden1.jpg",
      "http://www.biergarten-loewen.com/images/beer-garden2.jpg",
    ],
    location: {
      latitude: 53.570864,
      longitude: 10.023607,
    },
    socialMedia: {
      facebook: "http://www.facebook.com/biergartenloewen",
      twitter: "http://www.twitter.com/biergartenloewen",
      instagram: "http://www.instagram.com/biergartenloewen",
    },
    beerPrices: {
      pils: 3.9,
    },
  },
  {
    id: 5,
    name: "StrandPauli",
    address: "Hafenstraße 89, 20359 Hamburg",
    phone: "040-123456789",
    email: "info@alsterkneipe-hh.com",
    website: "http://www.alsterkneipe-hh.com",
    openingHours: {
      monday: "16:00 - 02:00",
      tuesday: "16:00 - 02:00",
      wednesday: "16:00 - 02:00",
      thursday: "16:00 - 02:00",
      friday: "16:00 - 03:00",
      saturday: "14:00 - 03:00",
      sunday: "14:00 - 02:00",
    },
    reviews: [
      {
        id: 1,
        username: "BeerLover92",
        rating: 5,
        comment: "Great atmosphere and friendly staff!",
      },
      {
        id: 2,
        username: "PubCrawler",
        rating: 4,
        comment: "Wide selection of beers and good music.",
      },
    ],
    specialties: ["Craft beers", "Burgers", "Sports screens", "Darts"],
    images: [
      "http://www.alsterkneipe-hh.com/images/bar1.jpg",
      "http://www.alsterkneipe-hh.com/images/bar2.jpg",
    ],
    location: {
      latitude: 53.559736,
      longitude: 9.969933,
    },
    socialMedia: {
      facebook: "http://www.facebook.com/alsterkneipehh",
      twitter: "http://www.twitter.com/alsterkneipehh",
      instagram: "http://www.instagram.com/alsterkneipehh",
    },
    beerPrices: {
      pils: 4.5,
    },
  },
  {
    id: 6,
    name: "Altes Mädchen",
    address: "Lagerstraße 28b, 20357 Hamburg",
    phone: "040-987654321",
    email: "info@waldschaenke-hh.com",
    website: "http://www.waldschaenke-hh.com",
    openingHours: {
      monday: "17:00 - 01:00",
      tuesday: "17:00 - 01:00",
      wednesday: "17:00 - 01:00",
      thursday: "17:00 - 01:00",
      friday: "17:00 - 02:00",
      saturday: "15:00 - 02:00",
      sunday: "15:00 - 01:00",
    },
    reviews: [
      {
        id: 1,
        username: "NatureLover",
        rating: 5,
        comment: "Lovely outdoor seating area surrounded by trees.",
      },
      {
        id: 2,
        username: "BeerFanatic",
        rating: 4,
        comment: "Nice selection of local craft beers.",
      },
    ],
    specialties: ["Outdoor seating", "Live music", "Grilled food", "Cocktails"],
    images: [
      "http://www.waldschaenke-hh.com/images/bar1.jpg",
      "http://www.waldschaenke-hh.com/images/bar2.jpg",
    ],
    location: {
      latitude: 53.573864,
      longitude: 10.004957,
    },
    socialMedia: {
      facebook: "http://www.facebook.com/waldschaenkehh",
      twitter: "http://www.twitter.com/waldschaenkehh",
      instagram: "http://www.instagram.com/waldschaenkehh",
    },
    beerPrices: {
      pils: 4,
    },
  },
  {
    id: 7,
    name: "Clouds Heaven's Bar & Kitchen",
    address: "Reeperbahn 1, 20359 Hamburg",
    phone: "040-123456789",
    email: "info@kneipenklause-hh.com",
    website: "http://www.kneipenklause-hh.com",
    openingHours: {
      monday: "18:00 - 02:00",
      tuesday: "18:00 - 02:00",
      wednesday: "18:00 - 02:00",
      thursday: "18:00 - 02:00",
      friday: "20:00 - 03:00",
      saturday: "20:00 - 03:00",
      sunday: "Geschlossen",
    },
    reviews: [
      {
        id: 1,
        username: "PartyAnimal",
        rating: 4,
        comment: "Great atmosphere and affordable drinks.",
      },
      {
        id: 2,
        username: "StudentLife",
        rating: 5,
        comment: "Awesome place to hang out with friends.",
      },
    ],
    specialties: ["Student-friendly prices", "Beer pong", "Board games"],
    images: [
      "http://www.kneipenklause-hh.com/images/bar1.jpg",
      "http://www.kneipenklause-hh.com/images/bar2.jpg",
    ],
    location: {
      latitude: 53.564788,
      longitude: 9.980221,
    },
    socialMedia: {
      facebook: "http://www.facebook.com/kneipenklausehh",
      twitter: "http://www.twitter.com/kneipenklausehh",
      instagram: "http://www.instagram.com/kneipenklausehh",
    },
    beerPrices: {
      pils: 2.5,
    },
  },
];
