export const matches = [
  {
    id: 1,
    homeTeamId: 1,
    awayTeamId: 2,
    date: "2023-07-01",
    time: "15:00",
    venue: "Blitz Arena",
    status: "scheduled",
  },
  {
    id: 2,
    homeTeamId: 3,
    awayTeamId: 4,
    date: "2023-07-02",
    time: "16:30",
    venue: "Tigerdome",
    status: "scheduled",
  },
  {
    id: 3,
    homeTeamId: 5,
    awayTeamId: 1,
    date: "2023-07-03",
    time: "18:00",
    venue: "Star Park",
    status: "scheduled",
  },
  {
    id: 4,
    homeTeamId: 2,
    awayTeamId: 3,
    date: "2023-07-04",
    time: "19:30",
    venue: "Falcon Arena",
    status: "scheduled",
  },
  {
    id: 5,
    homeTeamId: 4,
    awayTeamId: 5,
    date: "2023-07-05",
    time: "20:00",
    venue: "Goldfield",
    status: "scheduled",
  },
  {
    id: 6,
    homeTeamId: 1,
    awayTeamId: 3,
    date: "2023-07-06",
    time: "17:45",
    venue: "Blitz Arena",
    status: "scheduled",
  },
  {
    id: 7,
    homeTeamId: 2,
    awayTeamId: 4,
    date: "2023-07-07",
    time: "18:15",
    venue: "Tigerdome",
    status: "scheduled",
  },
  {
    id: 8,
    homeTeamId: 1,
    awayTeamId: 5,
    date: "2023-07-08",
    time: "19:00",
    venue: "Blitz Arena",
    status: "scheduled",
  },
  {
    id: 9,
    homeTeamId: 3,
    awayTeamId: 4,
    date: "2023-07-09",
    time: "20:30",
    venue: "Star Park",
    status: "scheduled",
  },
  {
    id: 10,
    homeTeamId: 2,
    awayTeamId: 3,
    date: "2023-07-10",
    time: "15:45",
    venue: "Tigerdome",
    status: "scheduled",
  },
  {
    id: 11,
    homeTeamId: 1,
    awayTeamId: 4,
    date: "2023-07-11",
    time: "17:30",
    venue: "Blitz Arena",
    status: "scheduled",
  },
  {
    id: 12,
    homeTeamId: 5,
    awayTeamId: 3,
    date: "2023-07-12",
    time: "19:15",
    venue: "Goldfield",
    status: "scheduled",
  },
];
