export const teams = [{

    "id": 1,
    "name": "Werder Bremen",
    "country": "Deutschland",
    "coach": "Ole Werner",
    "founded": 1899,
    "stadium": "Weserstadion",
    "capacity": 50000,
    "website": "http://www.werder.de",
    "logoColor": "00a629",
    "logoUrl": "https://i.imgur.com/YZk7qTS.png"
  },
  {
      "id": 2,
      "name": "FC Bayern München",
      "country": "Deutschland",
      "coach": "Julian Nagelsmann",
      "founded": 1900,
      "stadium": "Allianz Arena",
      "capacity": 75000,
      "website": "https://fcbayern.com",
      "logoColor": "DC052D",
      "logoUrl": "https://i.imgur.com/jJEsJrj.png"
  },
  {
    "id": 3,
    "name": "Borussia Dortmund",
    "country": "Deutschland",
    "coach": "Marco Rose",
    "founded": 1909,
    "stadium": "Signal Iduna Park",
    "capacity": 81365,
    "website": "https://www.bvb.de",
    "logoColor": "FDE100",
    "logoUrl": "https://i.imgur.com/OTj238a.png"
  },
  {
      "id": 4,
      "name": "RB Leipzig",
      "country": "Deutschland",
      "coach": "Jesse Marsch",
      "founded": 2009,
      "stadium": "Red Bull Arena",
      "capacity": 42045,
      "website": "https://www.dierotenbullen.com",
      "logoColor": "E60026",
      "logoUrl": "https://i.imgur.com/Rpwsjz1.png"
  },
  {
    "id": 5,
    "name": "1. FC Union Berlin",
    "country": "Deutschland",
    "coach": "Urs Fischer",
    "founded": 1966,
    "stadium": "Stadion An der Alten Försterei",
    "capacity": 22000,
    "website": "https://www.fc-union-berlin.de",
    "logoColor": "E70013",
    "logoUrl": "https://example.com/1-fc-union-berlin-logo.png"
  },
  {
    "id": 6,
    "name": "SC Freiburg",
    "country": "Deutschland",
    "coach": "Christian Streich",
    "founded": 1904,
    "stadium": "Schwarzwald-Stadion",
    "capacity": 24000,
    "website": "https://www.scfreiburg.com",
    "logoColor": "000000",
    "logoUrl": "https://i.imgur.com/r3mvi0h.png"
  },
  {
  "id": 7,
  "name": "Bayer 04 Leverkusen",
  "country": "Deutschland",
  "coach": "Gerardo Seoane",
  "founded": 1904,
  "stadium": "BayArena",
  "capacity": 30210,
  "website": "https://www.bayer04.de",
  "logoColor": "FF0000",
  "logoUrl": "https://i.imgur.com/Qf54aKx.png"
  },
  {
    "id": 8,
    "name": "VfL Wolfsburg",
    "country": "Deutschland",
    "coach": "Mark van Bommel",
    "founded": 1945,
    "stadium": "Volkswagen Arena",
    "capacity": 30000,
    "website": "https://www.vfl-wolfsburg.de",
    "logoColor": "007F00",
    "logoUrl": "https://i.imgur.com/ucqKV4B.png"
  },
  {
    "id": 11,
    "name": "1. FC Köln",
    "country": "Deutschland",
    "coach": "Steffen Baumgart",
    "founded": 1948,
    "stadium": "RheinEnergieStadion",
    "capacity": 50000,
    "website": "https://www.fc-koeln.de",
    "logoColor": "EC1E25",
    "logoUrl": "https://example.com/1-fc-koeln-logo.png"
  },
  {
    "id": 10,
    "name": "Borussia Mönchengladbach",
    "country": "Deutschland",
    "coach": "Adi Hütter",
    "founded": 1900,
    "stadium": "Borussia-Park",
    "capacity": 54067,
    "website": "https://www.borussia.de",
    "logoColor": "FDD518",
    "logoUrl": "https://i.imgur.com/KSIk0Eu.png"
  }]